<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LumaProfiles</AssemblyName>
    <RootNamespace>LumaProfiles</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\LumaProfiles.ico</ApplicationIcon>
    <Version>0.7.2</Version>
    <AssemblyTitle>Luma Profiles</AssemblyTitle>
    <Product>Luma Profiles by Código Limpio</Product>
    <Company>Código Limpio</Company>
    <Authors>Código Limpio</Authors>
    <Description>Biblioteca de perfiles de color para monitores Windows.</Description>
    <Copyright>Copyright © 2026 Código Limpio</Copyright>
    <RepositoryUrl>https://github.com/CodigoLimpioCo/luma-profiles</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\color-reference.png" />
    <Resource Include="Assets\CodigoLimpioLogo.png" />
    <Resource Include="Assets\LumaProfiles.ico" />
    <Content Include="Locales\*.lang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Locales\*.lang" />
  </ItemGroup>
</Project>
